<link rel="stylesheet" href="${resPath}/hplus/css/bootstrap.min.css">
<link rel="stylesheet" href="${resPath}/hplus/css/font-awesome.min.css" >
<link rel="stylesheet" href="${resPath}/hplus/css/animate.min.css" >
<link rel="stylesheet" href="${resPath}/hplus/css/style.min.css" >
<script type="text/javascript" src="${resPath}/hplus/js/jquery.min.js"></script>
<script type="text/javascript" src="${resPath}/hplus/js/bootstrap.min.js"></script>
<script type="text/javascript" src="${resPath}/hplus/js/layer/layer.min.js"></script>
<script type="text/javascript" src="${resPath}/hplus/js/extends.js"></script>